package ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(PRIMARY_LIGHT)
val PrimaryDark = Color(PRIMARY_DARK)
val BackgroundLight = Color(BACKGROUND_LIGHT)
val BackgroundDark = Color(BACKGROUND_DARK)
val SurfaceLight = Color(SURFACE_LIGHT)
val SurfaceDark = Color(SURFACE_DARK)
val MemoryLightBlue = Color(MEMORY_LIGHT_BLUE)
val MemoryBlue = Color(MEMORY_BLUE)

val LogoCardUp = Color(LOGO_CARD_UP)
val LogoCardDown = Color(LOGO_CARD_DOWN)
val LogoCardBackground = Color(LOGO_CARD_BACKGROUND)

val White = Color(WHITE)
val Black = Color(BLACK)
val LightGray = Color(LIGHT_GRAY)
val EmojiYellow = Color(EMOJI_YELLOW)
val AnimalGreen = Color(ANIMAL_GREEN)
val OceanBlue = Color(OCEAN_BLUE)
val PlantGreen = Color(PLANT_GREEN)
val BirdBlue = Color(BIRD_BLUE)
val FruitPurple = Color(FRUIT_PURPLE)
val FoodOrange = Color(FOOD_ORANGE)
val WeatherGray = Color(WEATHER_GRAY)
val MusicBlue = Color(MUSIC_BLUE)
val FireEngineRed = Color(FIRE_ENGINE_RED)
val HalloweenOrange = Color(HALLOWEEN_ORANGE)
val ThanksgivingBrown = Color(THANKSGIVING_BROWN)
val ChristmasRed = Color(CHRISTMAS_RED)
val ValentinePink = Color(VALENTINE_PINK)

val SimonGreenDark = Color(SIMON_GREEN_DARK)
val SimonGreenBright = Color(SIMON_GREEN_BRIGHT)
val SimonRedDark = Color(SIMON_RED_DARK)
val SimonRedBright = Color(SIMON_RED_BRIGHT)
val SimonYellowDark = Color(SIMON_YELLOW_DARK)
val SimonYellowBright = Color(SIMON_YELLOW_BRIGHT)
val SimonBlueDark = Color(SIMON_BLUE_DARK)
val SimonBlueBright = Color(SIMON_BLUE_BRIGHT)
